export const DropDownData = [
  {
    id: 0,
    tag: "briefs",
    headlines: "Have many secrets: Pak MP who said IAF pilot was",
    img:
      "https://static.toiimg.com/thumb/imgsize-52369,msid-78970387,width-141,resizemode-4/78970387.jpg",
    description: [
      "India's Covid cases go past 81 lakh with 48,648",
      "India's Covid-19 case fatality rate falls below 1.5",
      "Bottas upstages Hamilton to claim pole at Imola",
      "'Obamacare' sign-ups begin as millions more are",
      "IPL: Rohit is getting better and will be back soon:",
      "Strict law to put check on 'love jihad' in UP, says",
      "In a first, a desi airline to get a female boss",
      "RBI board needs to play like Rahul Dravid, not",
      "Nowhera Shaikh: Single mother in burqa ran",
      "Karnataka bypolls: Congress shocks BJP in Ballari",
      "We've planned well for Australia tour: Murali Vijay",
      "UP govt planning over 202-metre Ram statue structure",
      "Ducati unveils 3 new motorcycles ahead of EICMA 2018",
      "Air pollution may up autism risk in children: Study",
    ],
  },
  {
    id: 1,
    tag: "world",
    headlines: "Trump lashes out at doctors as Covid cases surge",
    img:
      "https://static.toiimg.com/thumb/imgsize-706859,msid-78965257,width-141,resizemode-4/78965257.jpg",
    description: [
      "China can no longer rely on old model of",
      "France struggles against spiral of online jihadist",
      "Biden's lead over Trump narrows slightly to 8 points",
      "Iraq reopens Tahrir Square, epicentre of revolt in",
      "Russia pledges help to Yerevan if fighting reaches",
      "'Remarks recounting release of Abhinandan have",
      "Three in custody in France following Nice attack",
      "Miscreants spray ‘Never forget 84’ on Dr Ambedkar",
      "Swiss protests for health worker rights, against",
      "Trump says nation is at crossroads with election",
      "China can no longer rely on old model of",
      "Why France incites such anger in Muslim world",
      "Have many secrets, says Pakistan MP who revealed",
      "Tanzania, once envy of the region, watches democracy",
    ],
  },
  {
    id: 2,
    tag: "business",
    headlines: "BoB slashes repo-linked lending rate by 15 basis",
    img:
      "https://static.toiimg.com/thumb/imgsize-38289,msid-78968723,width-141,resizemode-4/78968723.jpg",
    description: [
      "ICICI Bank Q2 profit jumps over six-folds to Rs",
      "'Nirmala wanted me out of finance ministry'",
      "Amazon says Future Retail is misleading public",
      "Ant Group's IPO sees record 3tn in retail demand",
      "Nafed floats bids for supply of 15k tonnes of onions",
      "Yamaha ties up with Amazon to sell accessories",
      "US jury tells Apple to pay 503m in patent case",
      "Bank of Baroda, Union Bank cut home loan rates",
      "AAI hands over Mangaluru airport to Adani group on",
      "Chevron, Exxon shrink spending as coronavirus cuts",
      "JSW Holdings September quarter profit drops to Rs 39",
      "Mitron TV launches 'Atmanirbhar Apps' to bring",
      "Goldman money funds' liquidity buffer swells before",
      "US judge blocks commerce department's order set to",
    ],
  },
  {
    id: 3,
    tag: "sports",
    headlines: "IPL: Clinical SRH beat RCB by 5 wickets to keep",
    img:
      "https://static.toiimg.com/thumb/imgsize-125454,msid-78972325,width-150,resizemode-4/78972325.jpg",
    description: [
      "Rohit is getting better and will be back soon,",
      "IPL: Mumbai thrash Delhi by 9 wickets, ensure top-2",
      "Bottas upstages Hamilton to claim pole for",
      "Yuvraj, Archer surprised by umpiring decision in",
      "Virat Kohli falls to Sandeep Sharma for seventh time",
      "EPL: Ziyech shines as Chelsea enjoy 3-0 win at",
      "There are lot of flaws in our game: Shreyas Iyer",
      "IPL 2020: Jasprit Bumrah snatches Purple Cap from",
      "Partizan's Stevanovic to join Man City in January",
      "Millman to face Mannarino in Astana Open final",
      "Hamilton predicts a boring race at beautiful Imola",
      " Ronaldo set for return on Juventus bench against",
      "Jobby Justin suffers injury, ruled out for entire",
      "RCB vs SRH Highlights: Sunrisers Hyderabad beat",
    ],
  },
  {
    id: 4,
    tag: "Entertainment",
    headlines: "BigStory: Corona effect on Bollywood",
    img:
      "https://static.toiimg.com/thumb/imgsize-160230,msid-78969608,width-150,resizemode-4/78969608.jpg",
    description: [
      "Aishwarya B'Day: Fans wish the eternal beauty",
      "Big B reminisces his film ‘Khoon Pasina’",
      "Big B mourns Sean Connery’s death",
      "Daniel Craig on Sean Connery's demise",
      "Kangana calls out Canada PM Justin Trudeau",
      "Kangana once again slams 'Haramkhor' remarks",
      "B'Town celebs mourn the loss of Sean Connery",
      "Theatre takes centre stage in Lucknow",
      "Festivities in the air",
      "Let’s light up our homes with positivity this",
      "Dilbagh Singh to team up with Haryanvi singer for",
      "Malayalam cinema once again looks at literature for",
      "Khushbu says she would love to act with Ravichandran",
      "Chethan Chandra will be seen in a travel-based",
    ],
  },
  {
    id: 5,
    tag: "TV",
    headlines: "BB4: Salman on nepotism; praises SRK & Akki",
    img:
      "https://static.toiimg.com/thumb/imgsize-114224,msid-78971958,width-150,resizemode-4/78971958.jpg",
    description: [
      "BB1: Kumar Sanu takes a U-turn; praises Jaan",
      "BB14: Salman lashes out at Rubina",
      "Ekta tells Smriti to 'kick out corona'",
      "Sandiip: Kavita is still in FIR character",
      "Aamir Ali's daughter starts walking; watch",
      "Shweta's husband on sexual harassment case",
      "Celebs who fought weight issues, depression",
      "Sshivani Durga gets eliminated from BB 11",
      "Dramatic twist in 'Ek Tha Raja Ek Thi Rani'",
    ],
  },
  {
    id: 6,
    tag: "lifestyle",
    headlines: "Forgiveness is the secret of happy marriage?",
    img:
      "https://static.toiimg.com/thumb/imgsize-594244,msid-78970278,width-141,resizemode-4/78970278.jpg",
    description: [
      "10 simple looks to try for Halloween",
      "COVID: Anxiety kept me up all nights",
      "Getting along with your ex based on sunsign",
      "Spooky Tales to read this Halloween weekend",
      "Tina Dutta's blue lehenga is stunning",
      "Harmful metals you must avoid while cooking",
      "Here’s your make-up guide for Karva Chauth",
      "Take inspiration from these celebs to turn vegan",
      "These easy food substitutes can help you turn vegan",
      "This specialty Assam tea was sold at a record price",
      "FHRAI welcomes mandatory registration rule for",
      "Experts suggest simple ways to lead a Vegan",
      "Is the idea of early dinner changing the concept of",
      "2020 is the year of men and pearl necklaces",
    ],
  },
  {
    id: 7,
    tag: "education",
    headlines: "Andhra schools to reopen on Monday, only 16 students",
    img:
      "https://static.toiimg.com/thumb/imgsize-156270,msid-78973781,width-141,resizemode-4/78973781.jpg",
    description: [
      "ICICI Bank Q2 profit jumps over six-folds to Rs",
      "'Nirmala wanted me out of finance ministry'",
      "Amazon says Future Retail is misleading public",
      "Ant Group's IPO sees record 3tn in retail demand",
      "Nafed floats bids for supply of 15k tonnes of onions",
      "Yamaha ties up with Amazon to sell accessories",
      "US jury tells Apple to pay 503m in patent case",
      "Bank of Baroda, Union Bank cut home loan rates",
      "AAI hands over Mangaluru airport to Adani group on",
      "Chevron, Exxon shrink spending as coronavirus cuts",
      "JSW Holdings September quarter profit drops to Rs 39",
      "Mitron TV launches 'Atmanirbhar Apps' to bring",
      "Goldman money funds' liquidity buffer swells before",
      "US judge blocks commerce department's order set to",
    ],
  },
  {
    id: 8,
    tag: "education",
    headlines: "Won't be surprised if Tejashwi becomes Bihar CM:",
    img:
      "https://static.toiimg.com/thumb/imgsize-112384,msid-78949071,width-141,resizemode-4/78949071.jpg",
    description: [
      "Nitish Kumar's credibility is completely destroyed:",
      " Tejashwi can't even spell 'Cabinet' while Nitish",
      " Karnataka: How elections will affect party bigwigs",
      "Facebook pulls down 3 ‘love jihad’ pages for",
      "How BJP sacrificed a Rajya Sabha seat to throw",
      "PM Modi changed nature of Indian politics: CM Yogi",
      "He is PM, he can speak anything: Tejashwi Yadav on",
      "'Certainly', says Scindia on whether Sonia Gandhi",
      "Like you saved yourself from Covid-19 with mask,",
      "I have chosen path of public service not of",
      "Bihar polls: 18.31 turnout till 11 am, Lakhisarai",
      "Rahul Gandhi to address two poll rallies in Bihar",
      "Bihar assembly elections: What’s at stake for PM",
    ],
  },
  {
    id: 9,
    tag: "Election",
    headlines: "Cases cross 5,000; 1-year-old among 165 dead",
    img:
      "https://static.toiimg.com/thumb/imgsize-87985,msid-78965199,width-141,resizemode-4/78965199.jpg",
    description: [
      "3-tier classification of hosps for infection",
      "Centre may extend lockdown as several states pitch",
      "Coronavirus cases in India rise to 39",
      "Horoscope Today, 9 March 2020",
      "PM’s social media abuzz with stories of grit",
      "FIR against Dhananjay Munde for remarks on cousin",
      "Maratha-fied BJP hopes to upend poll calculus",
      "Bihar polls: NDA's top leaders intensify attack on",
      "Bihar polls: Nitish Kumar announces to waive off",
      "Bihar: Tejashwi Yadav slams Nitish Kumar over Niti",
      "PM Modi to address four rallies in Bihar on Sunday",
      "RJD, Congress created obstacles in Ram temple",
      "RJD, Congress only make false promises, says Union",
      "Stage collapses during Pappu Yadav's campaign in",
    ],
  },
 
];
